CREATE TABLE `test_authority_user` (
  `id` varchar(50) NOT NULL,
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `mark_code` varchar(30) DEFAULT NULL,
  `account` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `sex` varchar(10) DEFAULT NULL,
  `theme` varchar(50) DEFAULT NULL,
  `mobile` varchar(50) DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `delete_mark` int(11) DEFAULT NULL,
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `create_user_id` varchar(50) DEFAULT NULL,
  `create_user_name` varchar(50) DEFAULT NULL,
  `modify_date` datetime DEFAULT NULL,
  `modify_user_id` varchar(50) DEFAULT NULL,
  `modify_user_name` varchar(50) DEFAULT NULL,
  `user_mark` varchar(1000) DEFAULT NULL,
  `unique_mark` varchar(100) DEFAULT NULL,
  `bu_id` varchar(100) DEFAULT NULL,
  `department_id` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4