server:
  port: 8081
  servlet:
    context-path: /tennetcn
think:
  checkmac:
    enabled: true
logging:
  config: classpath:logback-dev.xml
#think:
#  ratelimit:
#    enabled: true
#    policyList[0]:
#      type: URL
#      limit: 10
#      matcher: /tennetcn/home/hello